[package]
name = "lgh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35", features = [ "gfx", "ttf" ] }
vecmat = "0.7.7"
rand = "0.8.5"